apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ha-cluster-sentinel-d1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-ha-cluster-sentinel-lbl
  template:
    metadata:
      name: redis-ha-cluster-sentinel-p1
      labels:
        app: redis-ha-cluster-sentinel-lbl
    spec:
      restartPolicy: Always
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 100
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 100
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 100
      containers:
        - name: redis-ha-cluster-sentinel-c1
          image: redis-sentinel-ha-cluster:1.0
          resources:
            requests:
              memory: "100Mi"
              cpu: ".2"
            limits:
              memory: "2Gi"
              cpu: "2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 26379
          env:
            - name: SENTINEL
              value: "true"
